### ISSUE TITLE
Java Techdegree Courses to be Completed

### ISSUE THREAD

**Issue by dbriesz** [dbriesz/Treehouse#2]
## TODO

*Courses left to complete the Treehouse Java Techdegree*

* [ ] Java Data Structures
* [ ] Unit Testing in Java
* [ ] Dependency Management with Gradle

:tada: :computer: :nerd_face:
